export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const UPDATE_PROFILE_LOCALLY = 'UPDATE_PROFILE_LOCALLY';
export const UPDATING_FAVORITES_LOCALLY = 'UPDATING_FAVORITES_LOCALLY';
